### ISSUE TITLE
[feature request] Support nullValue?

### ISSUE THREAD

**Issue by muzuiget** [stemey/dojo-generate-form#50]
`nullValue` is different from `defaultValue`, the latter is the default value for input widget.

And I `nullValue` is if the field is not required, then the user didn't fill the field, then use the `nullValue` (instead of the JavaScript `null` value), for example

```
{
    code: "count"
    type: "number",
    required: false
}
```

We get `{count: null}`. 

If we support `nullValue`

```
{
    code: "count"
    type: "number",
    required: false,
    nullValue: -1
}
```

We get `{count: -1}`.

**Comment by stemey** [comment]
You can use a converter to convert between a dijit's value (null) and the model value (-1). 

An example converter: 
https://github.com/stemey/dojo-generate-form/blob/master/converter/isoDateConverter.js

Api to register a converter:
https://github.com/stemey/dojo-generate-form/blob/master/EditorFactory.js#L275
 
You probably want to set the defaultValue to -1 as well.

```
   {
    code: "count"
    convert:"myConverter",
    type:"number",
    defaultValue:-1
  }

```

**Comment by stemey** [comment]
Does that work for you?

**Comment by muzuiget** [comment]
Is not, my situation is, I am developing a game admin system, and I store the gform schema in database, then I can update schema(and the form) on the fly without re-deploy the system source code.

And the customer-support(AKA game master) they said the form default value not clear enough, that is, in some case, use the default value for a field, keep it empty is better than put a program magic number(or string) in it(also need to add a description let user know what it mean)

Register a converter need to change source code, and have to re-deploy them. And I don't known and  don't need to care the data model, so I can't write proper converter for them.

**Comment by stemey** [comment]
Ok, I think we could do something that uses a converter based on the "nullValue"-property. Have a look at the way the converter is selected by the Attributefactory: https://github.com/stemey/dojo-generate-form/blob/master/EditorFactory.js#L246.

If the converter property is missing then a simple converter that converts null to the nullValue and otherwise just leaves the value unaltered should be used in that method. That should do the trick. 

A specific converter defined either for the type or the converter-id will be aware of the nullValue if it is registered as a constructor function.

Try it out and if it works as desired I will pull the change request.

**Comment by muzuiget** [comment]
Yes, that I looking for a "global convert" to handle each field.
